# Generated by Django 5.1.4 on 2025-01-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
