# Generated by Django 5.1.4 on 2025-01-16 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
