# Generated by Django 5.1.4 on 2025-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0002_alter_order_ordered_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_items',
            field=models.JSONField(),
        ),
    ]
