# Generated by Django 5.1.4 on 2025-01-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0002_remove_order_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
