# Generated by Django 5.1.4 on 2025-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0003_remove_reviews_username_remove_reviews_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewer_name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='model_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
