# Generated by Django 5.1.4 on 2025-02-28 07:35

import mobile_sale.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_sale', '0006_alter_inventory_id_alter_order_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='imei_number',
            field=models.CharField(max_length=15, unique=True, validators=[mobile_sale.validators.validate_imei_number]),
        ),
    ]
